### ISSUE TITLE
@egjs/react-flicking exporting wrong type as object instead of components

### ISSUE THREAD

**Issue by darrist** [naver/egjs-flicking#449]
## Description
Hi, I'm not sure if v4.0 is officially ready however seeing its available on npm and official docs.

```
Check your code at AbsHeroSlider.tsx:194.
    at AbsHeroSlider (webpack-internal:///./src/components/abs/AbsHeroSlider.tsx:106:80)
    at div
    at ElementWrapper (/home/darris/Projects/torchlight-frontend/node_modules/react-scroll/modules/components/Element.js:35:5)
    at Element (/home/darris/Projects/torchlight-frontend/node_modules/react-scroll/modules/mixins/scroll-element.js:40:7)
    at div
    at div
    at MotionComponent (/home/darris/Projects/torchlight-frontend/node_modules/framer-motion/dist/framer-motion.cjs.js:421:30)
    at Main (webpack-internal:///./src/layouts/main/index.tsx:74:25)
    at WithAuthentication (webpack-internal:///./src/libs/withAuthentication.tsx:30:81)
    at Home
    at ModalProvider (/home/darris/Projects/torchlight-frontend/node_modules/react-modal-hook/dist/index.js:93:24)
    at Provider (/home/darris/Projects/torchlight-frontend/node_modules/react-redux/lib/components/Provider.js:21:20)
    at ApolloProvider (/home/darris/Projects/torchlight-frontend/node_modules/@apollo/client/react/context/context.cjs.js:32:21)
    at MyApp (webpack-internal:///./pages/_app.tsx:55:3)
    at AppWithTranslation
    at AppContainer (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/render.js:28:952)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at ReactDOMServerRenderer.render (/home/darris/Projects/torchlight-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:4053:17)
    at ReactDOMServerRenderer.read (/home/darris/Projects/torchlight-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/darris/Projects/torchlight-frontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:211:19)
    at Function.getInitialProps (webpack-internal:///./pages/_document.tsx:8:85)
    at loadGetInitialProps (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/render.js:54:1145)
    at async /home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:138:610)
    at async DevServer.renderToHTML (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/server/next-dev-server.js:36:578)
    at async DevServer.render (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:75:160)
    at async Object.fn (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/next-server.js:58:672)
    at async Router.execute (/home/darris/Projects/torchlight-frontend/node_modules/next/dist/next-server/server/router.js:25:67)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

## Steps to check or reproduce
1. Existing codebase with running v3
2. Update npm to v4

Anyways I'll be downgrading now, and thanks for the awesome work!

**Comment by WoodNeck** [comment]
Hello @darrist!
Thanks for the bug report :)
We've just released a newer version of react-flicking(v4.0.2) that fixes this issue

**Comment by MarleyAdamson** [comment]
> Hello @darrist!
> Thanks for the bug report :)
> We've just released a newer version of react-flicking(v4.0.2) that fixes this issue

Similar issue on the Vue release, only getting 4.0.1 on NPM, by the sounds of it 4.0.2 fixes it but hasn't been tagged as a release yet.

Getting `render function or template not defined in component: Flicking` whilst following the installation and quick start to the letter (NuxtJS SSR build).

**Comment by WoodNeck** [comment]
Hello @MarleyAdamson!
v4.0.2 released only for the react-flicking, as vue-flicking had no issue on our build config.

I've just tested the `@egjs/vue-flicking` v4.0.1 to test NuxtJS build on my local, and didn't get the similar issue.
Please check our [Nuxt SSR Guide](https://github.com/naver/egjs-flicking/blob/master/packages/vue-flicking/GUIDE_SSR.md) for more info :)

**Comment by WoodNeck** [comment]
@MarleyAdamson 
Sorry, my mistake!
There was an error in our documents importing Flicking.
I think you can fix that issue by changing your code like this

```diff
- import Flicking from "@egjs/vue-flicking";
+ import { Flicking } from "@egjs/vue-flicking";
```
