### ISSUE TITLE
React Testing Library - VanillaFlicking.getRenderingPanels is not a function

### ISSUE THREAD

**Issue by AzraelGarden** [naver/egjs-flicking#497]
## Description
When a test is created rendering the Flicking of egjs-flicking, the following console.error is shown in the console:

```
(node:29811) UnhandledPromiseRejectionWarning: TypeError: VanillaFlicking.getRenderingPanels is not a function
(node:29811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29811) UnhandledPromiseRejectionWarning: FlickingError: Camera is not attached to the Flicking instance. "init()" should be called first.
(node:29811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
 PASS  src/components/carousel/__tests__/Carousel.spec.tsx (5.106 s)
  ● Console
    console.error
      Error: Uncaught [TypeError: VanillaFlicking.getRenderingPanels is not a function]
          at reportException (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at innerInvokeEventListeners (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
          at invokeEventListeners (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
          at invokeGuardedCallback (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
          at beginWork$1 (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
          at performUnitOfWork (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:22779:12) TypeError: VanillaFlicking.getRenderingPanels is not a function
          at Flicking.__proto.render (/home/azraelgarden/membership-front/node_modules/@egjs/react-flicking/src/react-flicking/Flicking.tsx:136:9)
          at finishClassComponent (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:17485:31)
          at updateClassComponent (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:17435:24)
          at beginWork (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:19073:16)
          at HTMLUnknownElement.callCallback (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:3945:14)
          at HTMLUnknownElement.callTheUserObjectsOperation (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
          at innerInvokeEventListeners (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
          at invokeEventListeners (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
          at HTMLUnknownElementImpl._dispatch (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
          at HTMLUnknownElementImpl.dispatchEvent (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
          at HTMLUnknownElement.dispatchEvent (/home/azraelgarden/membership-front/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
          at Object.invokeGuardedCallbackDev (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:3994:16)
          at invokeGuardedCallback (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
          at beginWork$1 (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:23964:7)
          at performUnitOfWork (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:22779:12)
          at workLoopSync (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:22707:5)
          at renderRootSync (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:22670:7)
          at performSyncWorkOnRoot (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:22293:18)
          at /home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:11327:26
          at unstable_runWithPriority (/home/azraelgarden/membership-front/node_modules/scheduler/cjs/scheduler.development.js:468:12)
          at runWithPriority$1 (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
          at flushSyncCallbackQueueImpl (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:11322:9)
          at flushSyncCallbackQueue (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:11309:3)
          at scheduleUpdateOnFiber (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:21893:9)
          at Object.enqueueForceUpdate (/home/azraelgarden/membership-front/node_modules/react-dom/cjs/react-dom.development.js:12504:5)
          at Flicking.forceUpdate (/home/azraelgarden/membership-front/node_modules/react/cjs/react.development.js:384:16)
          at /home/azraelgarden/membership-front/node_modules/@egjs/react-flicking/src/react-flicking/Flicking.tsx:170:12
          at handler (/home/azraelgarden/membership-front/node_modules/@egjs/component/src/Component.ts:147:24)
          at forEach (/home/azraelgarden/membership-front/node_modules/@egjs/component/src/Component.ts:93:9)
          at Array.forEach (<anonymous>)
          at Flicking.trigger (/home/azraelgarden/membership-front/node_modules/@egjs/component/src/Component.ts:92:16)
          at Flicking.<anonymous> (/home/azraelgarden/membership-front/node_modules/@egjs/flicking/src/Flicking.ts:686:10)
          at step (/home/azraelgarden/membership-front/node_modules/@egjs/flicking/dist/flicking.js:190:21)
          at Object.next (/home/azraelgarden/membership-front/node_modules/@egjs/flicking/dist/flicking.js:121:18)
          at fulfilled (/home/azraelgarden/membership-front/node_modules/@egjs/flicking/dist/flicking.js:76:28)
          at process._tickCallback (internal/process/next_tick.js:68:7)

      at VirtualConsole.on.e (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:341:9)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)

    console.error
      The above error occurred in the <Flicking> component:

          at Flicking (/home/azraelgarden/membership-front/node_modules/@egjs/react-flicking/dist/flicking.cjs.js:438:24)
          at div
          at I (/home/azraelgarden/membership-front/node_modules/styled-components/dist/styled-components.cjs.js:1:18960)
          at Carousel (/home/azraelgarden/membership-front/src/components/carousel/Carousel.tsx:24:18)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:20085:23)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20118:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12318:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12339:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:20736:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:23426:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
```

Anyone else got this problem while creating tests with react-testing-library?

**Comment by WoodNeck** [comment]
Hello, @AzraelGarden!
I've never used react-testing-library, but I guess that error's occurred because that function `getRenderingPanels` is not bundled in our UMD module.
I can fix this, I'll leave comment here when it's done :)

**Comment by AzraelGarden** [comment]
@WoodNeck thanks for the quick response! Really appreciate this.
Probably have some workaround for this error with some jest mocks. I'll reply in the issue if I find a way too.
Thanks in advance =)

**Comment by AzraelGarden** [comment]
Just found a workaround for this problem, mocking the Node module with jest:
https://jestjs.io/docs/manual-mocks
