### ISSUE TITLE
Error massage being sent while flicking

### ISSUE THREAD

**Issue by dagim-shimelis** [naver/egjs-flicking#664]
## Description

the Flicking component is creating the carousel just fine but every time I try to move (flick) one of the child components an error is created by the Flicking component as follows.
```
Flicking.ts:58 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'key')
    at Flicking.ts:58:19
    at Array.map (<anonymous>)
    at getPanels (Flicking.ts:57:28)
    at normalizeChildren (runtime-core.esm-bundler.js:6408:42)
    at createBaseVNode (runtime-core.esm-bundler.js:6170:9)
    at _createVNode (runtime-core.esm-bundler.js:6263:12)
    at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:6128:12)
    at h (runtime-core.esm-bundler.js:7479:16)
    at Proxy.render (Flicking.ts:192:8)
    at renderComponentRoot (runtime-core.esm-bundler.js:893:44)
```
## Steps to check or reproduce

I have implementing the following code on Vue3
```
<Flicking class="px-3" :options="{ moveType: 'freeScroll', bound: true } ">
      <dev>1</dev>
      <dev>2</dev>
      <dev>3</dev>
      <dev>4</dev>
    </Flicking>
```

Is the issue in my way of implementing or is there some sort of bug in the package? and can you please explain what the error is about and how to fix it.

**Comment by WoodNeck** [comment]
Hello @dagim-shimelis!
Try using other tags, changing `<dev>` to other tags like `<div>` fixed the issue for me.

**Comment by dagim-shimelis** [comment]
OH I apologize that was a silly **typo** while writing this issue but I see that I should have been more descriptive of the exact code I am working with. I have edited the Issue and dived a little deeper into the problem and the error only shows up when a `v-click` event listener & `:class` is added into the `div` tag.

**Comment by WoodNeck** [comment]
Good to hear that :)
I think then maybe that click event listener could be the cause.
I've just tested that using `:class` and `@click` doesn't trigger any error, I think maybe something more is included in your case.

- https://codesandbox.io/s/charming-ramanujan-fwkghv?file=/src/App.vue

Check the above demo I made whether it helps, and please let me know the actual code if it doesn't resolves
Also, you can use `select` event instead :)

**Comment by dagim-shimelis** [comment]
The demo helped in working out the issue and it's fully resolved now.
Thank you so much for your help :)

**Comment by wbm-sbasler** [comment]
I don't know if your problem still exists, but I ran into the same error.  Every time I used the pagination buttons, or the autoslide is executed, the error occurred in the console.  
Adding a `:key` to the slides, fixed the problem for me.
```
<Flicking>
      <div v-for="(slide, index) in slides">
        <Hero v-bind="slide" :key="index" />
      </div>
</Flicking>
```
