### ISSUE TITLE
Nuxt2 version production mode issue. Import style through cdn is not a solution.

### ISSUE THREAD

**Issue by whatamelon** [naver/egjs-flicking#714]
설치 및 세팅 후 개발서버에서는 괜찮지만, production mode로 실행 시 해당 에러가 발생하고 있습니다.

```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (http://15.164.213.231/_nuxt/685ab0b.js:2:41695)
    at m (http://15.164.213.231/_nuxt/685ab0b.js:2:54581)
    at v (http://15.164.213.231/_nuxt/685ab0b.js:2:54318)
    at w (http://15.164.213.231/_nuxt/685ab0b.js:2:54667)
    at R (http://15.164.213.231/_nuxt/685ab0b.js:2:58052)
    at R (http://15.164.213.231/_nuxt/685ab0b.js:2:57987)
    at R (http://15.164.213.231/_nuxt/685ab0b.js:2:57987)
    at R (http://15.164.213.231/_nuxt/685ab0b.js:2:57987)
    at f.__patch__ (http://15.164.213.231/_nuxt/685ab0b.js:2:58422)
    at t._update (http://15.164.213.231/_nuxt/685ab0b.js:2:35134)   
```

세팅은 

**css**

_nuxt.config.js_

```

 link: [
      {
        rel: 'stylesheet',
        href: 'https://unpkg.com/@egjs/flicking/dist/flicking.css'
      },
      {
        rel: 'stylesheet',
        href: 'https://unpkg.com/@egjs/flicking-plugins@4.4.0/dist/flicking-plugins.css'
      },
      {
        rel: 'stylesheet',
        href: 'https://unpkg.com/@egjs/flicking-plugins@4.4.0/dist/pagination.css'
      },
      {
        rel: 'stylesheet',
        href: 'https://unpkg.com/@egjs/flicking-plugins@4.4.0/dist/arrow.css'
      }
],

plugins: [
    { src: '~/plugins/flicking.js', ssr: false },
]
```

**js**

_flicking.js_
```
import Vue from "vue";
import VueFlicking from "@egjs/vue-flicking";

Vue.use(VueFlicking);
```

**Component**

```
<template>
    <section class="tw-w-full tw-mb-8">
            <flicking
            class="flicking"
            :options="{ circular: true, gap: 1, duration: 600, deceleration: 0.0025, easing: x => 1 - Math.pow(1 - x, 3) }"
            :plugins="plugins"
            >
                <div 
                v-for="(BannerDTO,index) in $store.getters.HOME_TOP_BANNERS"
                :key="index"
                >
                </div>
                <span slot="viewport" class="flicking-arrow-prev is-thin "></span>
                <span slot="viewport" class="flicking-arrow-next is-thin "></span>
                <div slot="viewport" class="flicking-pagination banner_slide-pagination"></div>
            </flicking>
    </section>
</template>

<script>
import { AutoPlay, Arrow, Pagination } from "@egjs/flicking-plugins";
export default {
    props:{
        topBanners:{
            type:Array
        }
    },
    data() {
        return {
            plugins:[new AutoPlay(5000, "NEXT"), new Arrow(), new Pagination({ type: 'fraction' }) ]
        }
    },
    created() {
        if(this.$device.isMobileOrTablet == true) {
            this.plugins = [new AutoPlay(5000, "NEXT"), new Pagination({ type: 'fraction' }) ]
        } else {
            this.plugins = [new AutoPlay(5000, "NEXT"), new Arrow(), new Pagination({ type: 'fraction' }) ]
        }
    },
}
</script>
```

**Nuxt2
flicking
flicking-plugins**

위의 두개 라이브러리를 사용중입니다.

페이지 진입까지는 가능하고 진입 후 페이지 그리기 까지 하지만 그 이상의 function의 동작이 멈춥니다.

확인부탁드립니다~

**Comment by malangfox** [comment]
안녕하세요 @whatamelon님.

남겨주신 현상은 Nuxt에 작성된 [이슈](https://github.com/nuxt/nuxt.js/issues/9147)들과 유사한 현상처럼 보이며 hydration error로 추정됩니다. 
해당 이슈에서 에러에 대한 해결 방법을 정리하여 둔 글이 [링크](https://blog.lichter.io/posts/vue-hydration-error/)되어 있는데요, 혹시 연관 이슈들을 확인하여보시고 안내된 방법을 시도하여보실 수 있으실까요?

**Comment by whatamelon** [comment]
말씀해주신 내용 바탕으로 고민해보았구요. <client-only> 및 라이프사이클 관리로 해결했습니다! 감사합니다!
