### ISSUE TITLE
[Vue3-flicking] TypeError: Cannot set properties of undefined (setting 'hasError')

### ISSUE THREAD

**Issue by nickdrim** [naver/egjs-flicking#745]
## Description
Hello team!

We noticed from our error monitor that when the first image of our carousel can not be loaded we get the following error.

```
TypeError: Cannot set properties of undefined (setting 'hasError')
  at onError(src/ImReadyManager.ts:241:10)
  at ? (src/ImReadyManager.ts:69:14)
  at ? (src/Component.ts:98:16)
  at Array.forEach(<anonymous>)
  at trigger(src/Component.ts:96:16)
  at onError(src/loaders/Loader.ts:95:10)
  at handler(src/ImReadyManager.ts:188:14)
  at ? (src/Component.ts:93:9)
  at Array.forEach(<anonymous>)
  at trigger(src/Component.ts:92:16)
  at onError(src/ImReadyManager.ts:268:10)
  at ? (src/ImReadyManager.ts:69:14)
  at ? (src/Component.ts:98:16)
  at Array.forEach(<anonymous>)
  at trigger(src/Component.ts:96:16)
  at onError(src/loaders/Loader.ts:95:10)
  at ? (src/loaders/Loader.ts:131:12)
  at i(src/helpers.ts:95:1)
```

Version: "@egjs/vue3-flicking": "4.10.2"

## Steps to check or reproduce

1. Create a flicking carousel with images
2. Set the first image of the carousel to return 404

And you should notice that the error is triggered.

Could you please catch this error or is there a way we can catch it because it creates a lot of noise in our monitor tool?

Thanks in advance!

**Comment by nickdrim** [comment]
Hello again @malangfox,

I managed to replicate it and updated your [demo](https://codesandbox.io/s/flicking-image-404-error-forked-wk9o8h?file=/src/components/Demo.vue) closer to ours. Turns out that adding a div wrapper with v-for and img with lazy loading seems to create the problem

**Comment by malangfox** [comment]
There are a few things we want to check in the process of reproducing this error.

I guess using v-for and loading="lazy" at the same time when `resizeOnContentsReady` option is true causes this error.
Could you check this condition is correct with your own implementation using Flicking?

Also, when we download the demo we modified and check the results of `npm run serve` or `npm run build`, no error occurs. Could this error can be reproduced when you test in the local environment?

**Comment by nickdrim** [comment]
Hello again!  We removed `resizeOnContentsReady` and it seems to be working fine without it! Thanks a lot for the help!

FYI this error could also be reproduced locally.

Lastly do you have any plans to fix this error in case we need the option in the future?

**Comment by malangfox** [comment]
We will fix this bug and leave a comment when a patch is released.
Thanks for reporting the bug with details!

**Comment by malangfox** [comment]
Hello @nickdrim.

vue3-flicking 4.10.3 has been released, which fixes this issue.
Try using version 4.10.3 and let us know if you encounter any problem.
